---

baseurl: "/"
languageCode: "en-us"
title: "Monitoring"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Operating the Foundry"
    notes: |
      In this section, we cover the basics of monitoring in Cloud Foundry.
