---
jobs:
- name: publish
  public: true
  plan:
  - get: summit-training-classes
    trigger: true
  - task: generate
    file: summit-training-classes/basics/ci/build.yml
  - put: cf
    params:
      manifest: summit-training-classes/basics/ci/manifest.yml
      path: built/

resources:
- name: summit-training-classes
  type: git
  source:
    uri: https://github.com/cloudfoundry/summit-training-classes.git
    branch: master

- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: owolf@anynines.com
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false
