---

baseurl: "/"
languageCode: "en-us"
title: "Buildpacks"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Cloud Foundry Basics"
    notes: |

      In this section, we cover the basics of Buildpacks.
