---

baseurl: "/"
languageCode: "en-us"
title: "Service Discovery"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Going Cloud Native"
    notes: |

      In this section, we cover the basics of service discovery and access.
