---

baseurl: "/"
languageCode: "en-us"
title: "Scaling"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Operating the Foundry"
    notes: |
      In this section, we cover scaling cloud foundry and scaling applications.
