---

baseurl: "/"
languageCode: "en-us"
title: "Cloud Foundry : Zero to Hero"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Cloud Foundry Basics"
    notes: |

      A user's introduction to Cloud Foundry.
