---

baseurl: "/"
languageCode: "en-us"
title: "Bosh Interactions & Availability"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Operating the Foundry"
    notes: |
      In this section, we will look at the HA capabilities of bosh deployed clusters.
