---

baseurl: "/"
languageCode: "en-us"
title: "Upgrading"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Operating the Foundry"
    notes: |
      In this section, we cover upgrading cloud foundry.
