---

baseurl: "/"
languageCode: "en-us"
title: "Bosh Basics"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Operating the Foundry"
    notes: |
      In this section, we will cover the basics of cloud and bosh.  Everyone will deploy their own cloud using vagrant and deploy cloudfoundry to it using bosh.
