---

baseurl: "/"
languageCode: "en-us"
title: "Pushing Your First App"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Cloud Foundry Basics"
    notes: |

      In this section, we cover the basics of pushing an app to cloud foundry.
